kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "/etc/kubernetes/pki/kube-proxy.kubeconfig"
mode: "iptables"
clusterCIDR: "${K8S_CLUSTER_POD_SUBNET}"