#!/usr/bin/env bash

. /usr/local/scripts/common.sh

# https://kubernetes.io/docs/reference/access-authn-authz/node/#overview

cluster="${1}"
name="${2}"
user="${3}"

cd /etc/kubernetes/pki/

kubectl config set-cluster ${cluster} \
  --certificate-authority=ca.crt \
  --embed-certs=true \
  --server=https://${K8S_CLUSTER_DOMAIN}:6443 \
  --kubeconfig=${name}.kubeconfig

kubectl config set-credentials ${user} \
  --client-certificate=${name}.crt \
  --client-key=${name}.key \
  --embed-certs=true \
  --kubeconfig=${name}.kubeconfig

kubectl config set-context default \
  --cluster=${cluster} \
  --user=${user} \
  --kubeconfig=${name}.kubeconfig

kubectl config use-context default \
  --kubeconfig=${name}.kubeconfig
